# Generated by Django 5.0.1 on 2024-03-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_types',
            field=models.CharField(blank=True, choices=[('FASCILITY', 'fascility'), ('LOGISTICS', 'logistics'), ('KITCHEN', 'kitchen')], max_length=20, null=True),
        ),
    ]
