# Generated by Django 5.0.1 on 2024-02-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('users', '0002_alter_cohort_is_active_alter_cohortmember_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='facillitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_facillitator', to='users.imuser'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('CLASS_SESSIONS', 'Class Sessions'), ('WELLNESS_SESSIONS', 'Wellness seesions'), ('GUEST_LECTURE', 'Guest lecture')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_organizer', to='users.imuser'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='repeat_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20, null=True),
        ),
    ]
